# main text of home
name: Indranil Biswas
bio: Final Year Undregraduate, majoring in CS<br>Machine Learning, NLP and interdisciplinary practitioner.

# twitter summary info
description: A blog about technology and personal 'life-marks' stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://drive.google.com/file/d/1k4c29UcGXSIJNi3qIniv5aUQsYBrrgSG/view?usp=sharing

url: https://glitch401.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
#disqus:
#  shortname: # enter this from your disqus account
#  categories: # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: indranil.biswas.520
#twitter: indranilbiswas7
# google: mygoogle
#instagram: foolish_hunger
# pinterest: mypinterest
github: glitch401
linkedin: indranilbiswas7
# youtube: myyoutube
# spotify: myspotify

# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
#medium: indranilbiswas7
# vimeo: myvimeo
# lanyrd: mylanyrd
email: indranilbiswas7@gmail.com

authors:
    indranilbiswas:
        name: Indranil Biswas
        bio: a nice chap
# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
#paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true
skills: false

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links:

# show author block at the end of a post ?
show-author: false

# do you want some animations?
animation: true

sass:
    sass_dir: _sass
    style: :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, .travis.yml, screen-shot.png, travis.sh, tasks]
